llm-d/llm-d-inference-scheduler

- pkg/config/config.go
- pkg/scheduling/pd/scheduler.go
add constants for parts of  environment variables names + make sure that all GIE scorer env vars names consistent
> Fixes according to review comments in issue #109

- DEVELOPMENT.md
- Makefile
- scripts/kind-dev-env.sh
This PR includes:
- Add clean-env-dev-kind target to the makefile
- Fix vllm-sim image version (use the official one-dev is not compiled from this git)
That makes the target ```env-dev-kind``` run properly.
> [Build]: Update clean-env-dev-kind target  in Makefile and fix vllm-sim image version 

- Makefile
This is a cleanup/maintenance PR. The `version.json` file was removed from the project (consolidated to `main`, releases are triggered on git tags, etc.). Thus removing all references and targets in Makefile that make use of the version file.
There are additional, lingering, settings for DEV_VERSION and PROD_VERSION in the Makefile (defaulting to 0.0.x).
Changing them requires some additional work and investigation (e.g., get default PROD_VERSION from GH tags and or releases, set DEV_VERSION based on current SHA, etc.) which are beyond the scope of this PR.
Fix #133
> remove version.json references from Makefile

- deploy/components/inference-gateway/deployments.yaml
- deploy/components/inference-gateway/httproutes.yaml
- deploy/components/inference-gateway/inference-models.yaml
- deploy/components/inference-gateway/inference-pools.yaml
- deploy/components/inference-gateway/rbac.yaml
- deploy/components/inference-gateway/service-accounts.yaml
- deploy/components/inference-gateway/services.yaml
- deploy/components/vllm-sim-pd/deployments.yaml
- deploy/components/vllm-sim/deployments.yaml
- deploy/environments/dev/base-kind-istio/destination-rules.yaml
- deploy/environments/dev/base-kind-istio/patch-deployments.yaml
- scripts/kind-dev-env.sh
Add MODEL_NAME to the deploy scripts, and allow it to be changed.
> fix: Add MODEL_NAME to kind deploy

- DEVELOPMENT.md
Hello, I'm fairly new to the llm-d community but found some small issues trying to get started. Upon following the DEVELOPMENT.md instructions, I ran into a few issues running `make env-dev-kind`. Namely, on a Fedora 41 system, I found that:
- Kustomize requires an explicit installation aside from kubectl or else you would get an error saying kustomize was not found
- `llm-d-inference-sim` by default required a tag of `v0.1.0` as shown here after having built a sim docker image with the tag `0.0.4`:
```+ kind --name llm-d-inference-scheduler-dev load docker-image ghcr.io/llm-d/llm-d-inference-sim:v0.1.0
ERROR: image: "ghcr.io/llm-d/llm-d-inference-sim:v0.1.0" not present locally
make: *** [Makefile:291: env-dev-kind] Error 1
```
> DEVELOPMENT.md minor fixes

- pkg/scheduling/pd/scheduler.go
While browsing the code, I spotted this line that would break if the
IP address was IPv6. Use the Go standard library helper to safely join
a host and port, which knows how to handle IPv6 properly.
Signed-off-by: Russell Bryant <rbryant@redhat.com>
> Make URL construction IPv6-compatible

- docs/architecture.md
- pkg/config/config.go
- pkg/scheduling/pd/scheduler.go
- pkg/scheduling/pd/scheduler_test.go
- pkg/scheduling/plugins/scorer/prefix_aware.go
- pkg/scheduling/plugins/scorer/prefix_aware_test.go
- pkg/scheduling/plugins/scorer/prefix_store.go
- pkg/scheduling/plugins/scorer/prefix_store_test.go
Use environment variables to define prefix scorer configuration
> Prefix aware scorer initialization

- docs/create_new_filter.md
after merging PR #179, in post merge CI found a broken link to by_labels.go in the docs markdown file.
This PR fixes the link.
> fixed by labels link in the docs example markdown

- go.mod
- go.sum
- pkg/plugins/filter/by_labels.go
- pkg/plugins/filter/pd_role_filter.go
- pkg/plugins/pre-request/pd_prerequest.go
- pkg/plugins/profile/pd-profile-handler.go
- pkg/plugins/scorer/kvcache-aware.go
- pkg/plugins/scorer/load_aware_scorer.go
- pkg/plugins/scorer/prefix_aware.go
- pkg/plugins/scorer/prefix_aware_test.go
- pkg/plugins/scorer/session_affinity.go
This PR updates llm-d-scheduler plugins after some changes were made to interfaces in GIE upstream.
more concretely, the following PRs were merged in GIE:
- https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1038
- https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1040
the last one was also considered as a potential improvement that might help in #189 (cc @kfirtoledo).
once this PR merges, Kfir can explore moving some P/D specifics out of the prefix scorer and into the ProcessResults function of the PDProfileHandler.
> sync with latest GIE after some changes to the scheduling plugins

- DEVELOPMENT.md
- Makefile
- deploy/components/inference-gateway/inference-models.yaml
- deploy/components/vllm-sim/deployments.yaml
- deploy/environments/dev/kubernetes-kgateway/gateway-parameters.yaml
- deploy/environments/dev/kubernetes-kgateway/kustomization.yaml
- deploy/environments/dev/kubernetes-kgateway/patch-deployments.yaml
- deploy/environments/dev/kubernetes-kgateway/patch-gateways.yaml
- deploy/environments/dev/kubernetes-kgateway/secret.yaml
- scripts/kind-dev-env.sh
- scripts/kubernetes-dev-env.sh
Add support for development on a Kubernetes cluster using scripts/kubernetes-dev-env.sh.
The script will be created in the namespace user gateway+EPP+VLLM for development.
In addition, adding two Makefiles to target for deployment and cleaning: `env-dev-kubernetes` and `clean-env-dev-kubernetes `
> build: add support for development on kubernetes cluster

- pkg/plugins/pre-request/pd_prerequest.go
This PR removes the protocol setting from the prefill endpoint header.
as agreed in #219 and in https://github.com/llm-d/llm-d-routing-sidecar/issues/38#issuecomment-3033538349, we move the responsibility on setting the protocol to the sidecar, where it should be possible to decide to use selected protocol. 
fix #219
> prefill header is set in the form of ip:port

- pkg/scheduling/pd/scheduler_test.go
This PR updates the scheduler unit tests.
in the existing tests (before this PR), the tests were not testing the single unit. that is, the tests included loaded configuration from file and setting the scheduler config via that path.
a unit-test by definition should test the scheduler unit, while completely decoupling from how the scheduler was configured.
we don't want scheduler unit-tests to fail if there is a bug in the config api (loading configuration from file).
the config api itself has unit-tests in GIE upstream and doesn't have to be tested here (we can add tests in llm-d but IMO this is redundant and not necessary).
instead of setting the scheduler plugins via config file, the test was updated to set scheduler plugins via code.
> updated scheduler unit test

- pkg/scheduling/pd/scheduler_test.go
This PR removes the need to compare concrete scores in the scheduler unit-test.
we don't want the scheduler unit-test to fail in case the scorer changed its default value or its internal calculations (e.g., scores range chage).
instead, we can ignore the specific score and just make sure that the expected pod is selected.
> ignore score in scheduler unit test

- DEVELOPMENT.md
- scripts/kubernetes-dev-env.sh
This PR addresses the following issues:
1.    Adds missing Gateway API CRDs in the cluster
2.    Typos or misconfiguration for the Redis deployment
Issue # https://github.com/llm-d/llm-d-inference-scheduler/issues/258
> Fixes for Steps to Build a Kubernetes Development Environment

- docs/architecture.md
- pkg/plugins/scorer/load_aware_scorer.go
Removing references to LoRA since that functionality is handled in upstream. Also removed reference to 'QueuingThresholdLoRA' as I couldn't find any reference to it in the llm-d org. Small grammatical flow changes
> small updates to documentation

- Makefile
Fix Makefile syntax issues by correcting shell command substitution and indentation errors.
Resolves "Unsupported Linux package manager" error when running `make download-zmq` on Ubuntu systems. logs: 
```
Checking if ZMQ is already installed...
Installing ZMQ dependencies...
Unsupported Linux package manager. Install libzmq manually.
make: *** [Makefile:339: download-zmq] Error 1
```
The issue was caused by incorrect Make variable substitution syntax, where $(command -v apt)was being evaluated by Make at parse time instead of being passed to the shell for runtime evaluation.
It also fixed an indentation error in `uninstall-docker`.
> fix: correct shell command substitution syntax in Makefile

- docs/architecture.md
Add a reference to creating a new plugin guide in architecture.md
In addition:
- break long lines and introduce leading space where a continuation is needed.
- fix typos
- add blank line before/after code snippets (e.g., YAML examples)
Fix #260
> add reference to writing a new plugin

- .github/dependabot.yml
> Remove non-existent labels from dependabot configuration

- Dockerfile
- Makefile
> Add build metadata to Docker image

- .github/workflows/prow-github.yml
- .github/workflows/prow-pr-automerge.yml
- .github/workflows/prow-pr-remove-lgtm.yml
- .github/workflows/re-run-action.yml
- .prowlabels.yaml
- OWNERS
- OWNERS_ALIASES
Issue: https://github.com/llm-d/llm-d-inference-scheduler/issues/148
This commit adds GitHub Actions workflows for Prow CI/CD pipeline, including the following files:
- Prow GitHub workflow
- PR auto-merge workflow
- PR LGTM removal workflow
- Re-run action workflow
- Prow labels configuration
- OWNERS file
> Add Prow GitHub Actions

- Makefile
This PR fixes issues with building images and downloading the tokenizer library on MacOS.
In particular:
1. It hard codes the TARGETOS passed into the image builder as linux
2. It overrides the architecture used when downloading the toenizer to be x86_64 and not amd64 on Intel based Macs
**Note:** this uses GNU Makefile extensions. Is this ok?
fix: #293
> fix: Makefile fixes for MacOS

- docs/architecture.md
- go.mod
- go.sum
- pkg/plugins/register.go
- pkg/plugins/scorer/active_request.go
- pkg/plugins/scorer/active_request_test.go
Introduced a new load-based scorer that looks at the active requests being served through the epp instance. Each request is tracked individually with its own TTL to ensure accurate timeout handling. Pods with fewer active requests receive higher scores.
The scorer maintains two data structures for efficiency:
- A cache of individual requests with TTL for automatic cleanup
- A count map for fast O(1) lookup during scoring
Scores are normalized to a range of 0-1, where pods with fewer active requests get higher scores.
> [feature] Added Active-Request-Scorer

- pkg/plugins/filter/by_label_selector_test.go
Test code for filtering based on k8s LabelSelector.
Besides tests, there's example code to show selection of Pods using ByLabelSelector filter with configurations to match #220.
Fix #220
> ByLabelSelector filter tests

- .typos.toml
This is blocking PR #320 to sync with IGW latest RC.
we should exclude go.sum and go.mod from typos check
> fixed a bug where typos check is checking go.mod and go.sum

- Makefile
current Makefile doesn't show some of the make targets when running `make help`.
for example, none of the tests targets are shown.
this PR is fixing this.
no logic change.
> minor tweaks to Makefile

- Dockerfile
Cleaning dnf cache reduces img size by ~80MB
refs #125
> Reduce img size by cleaning dnf cache
